import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getServerSession } from "@/server/auth";
import { redirect } from "next/navigation";
import { TRPCReactProvider } from "./TrpcProvider";
import { AntdProvider } from "./AntdProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession()
  console.log(session)
  // if (!session?.user) {
  //   console.log("no session")
  //   redirect("/api/auth/signin")
  // }
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TRPCReactProvider>
          <AntdProvider>
            {children}
          </AntdProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
