name: CI/CD Pipeline

# 触发条件：当推送到 master 分支或创建 PR 时
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # 代码检查和测试任务
  test:
    runs-on: ubuntu-latest
    
    steps:
    # 1. 下载代码
    - name: 检出代码
      uses: actions/checkout@v4
    
    # 2. 设置 Node.js 环境
    - name: 设置 Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    # 3. 安装依赖
    - name: 安装依赖
      run: npm ci
    
    # 4. 代码检查
    - name: 运行 ESLint
      run: npm run lint
    
    # 5. 类型检查
    - name: TypeScript 类型检查
      run: npx tsc --noEmit
    
    # 6. 构建项目
    - name: 构建项目
      run: npm run build

  # 部署任务（仅在 master 分支）
  deploy:
    needs: test  # 只有测试通过才会部署
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    
    steps:
    - name: 部署到 Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.ORG_ID }}
        vercel-project-id: ${{ secrets.PROJECT_ID }}
        vercel-args: '--prod' 